snapcraft-version: 8.14.5.post106
snapcraft-started-at: '2026-04-27T17:03:19.569775Z'
snapcraft-os-release-id: ubuntu
snapcraft-os-release-version-id: '26.04'
name: network-manager
version: 1.54.3-1
summary: Network Manager
description: |
  NetworkManager is a system network service that manages your network
  devices and connections, attempting to keep active network connectivity
  when available. It manages ethernet, WiFi, mobile broadband (WWAN) and
  PPPoE devices, provides VPN integration with a variety of different
  VPN services.
  Please find the source code for this track at:
    https://github.com/canonical/network-manager-snap/tree/snap-26
base: core26
grade: stable
confinement: strict
apps:
  nmcli:
    command: usr/bin/nmcli
    plugs:
    - nmcli
  nmtui:
    command: usr/bin/nmtui
    plugs:
    - nmcli
  nmtui-connect:
    command: usr/bin/nmtui-connect
    plugs:
    - nmcli
  nmtui-edit:
    command: usr/bin/nmtui-edit
    plugs:
    - nmcli
  nmtui-hostname:
    command: usr/bin/nmtui-hostname
    plugs:
    - nmcli
  networkmanager:
    command: bin/networkmanager
    daemon: simple
    slots:
    - service
    plugs:
    - modem-manager
    - ppp
    - network-setup-observe
    - wpa
    - firewall-control
    - hardware-observe
    - network-setup-control
    - login-session-observe
    - network-observe
    - network-control
parts:
  networkmanager-common:
    plugin: dump
    source: snap-common
    stage-packages: []
    stage: []
    prime: []
    build-packages: []
  changelog:
    plugin: nil
    override-build: 'cp "/build/network-manager-snap-26"/ChangeLog "$CRAFT_PART_INSTALL"/ChangeLog

      '
    organize:
      ChangeLog: snap/ChangeLog
    stage-packages: []
    stage: []
    prime: []
    build-packages: []
  stack-snaps-tools:
    plugin: nil
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/stack-snaps-tools
    source-type: git
    build-packages:
    - dpkg-dev
    - git
    stage-packages:
    - adduser=3.153ubuntu1
    - dnsmasq-base=2.92-1
    - libcurl3t64-gnutls=8.18.0-1ubuntu2
    - libjansson4=2.14-2build4
    - libldap2=2.6.10+dfsg-1ubuntu5
    - libmm-glib0=1.25.95-1ubuntu1
    - libndp0=1.9-1build1
    - libnewt0.52=0.52.25-1ubuntu3
    - libnftables1=1.1.6-1
    - libnghttp2-14=1.68.0-2
    - libnm0=1.54.3-2ubuntu3
    - libpsl5t64=0.21.2-1.1build2
    - librtmp1=2.4+20151223.gitfa8646d.1-3
    - libsasl2-2=2.1.28+dfsg1-9ubuntu3
    - libslang2=2.3.3-5build1
    - libssh2-1t64=1.11.1-1build2
    - libteamdctl0=1.31-1build4
    - network-manager=1.54.3-2ubuntu3
    override-build: |
      set -ex
      find "$CRAFT_PART_INSTALL"/ -type f,l \
                -not -path "$CRAFT_PART_INSTALL"/'usr/share/doc/network-manager*' \
                -not -path "$CRAFT_PART_INSTALL"/'usr/share/doc/libnm0*' \
           -and -not -path "$CRAFT_PART_INSTALL"/'usr/share/doc/dnsmasq-base*' \
           -delete
      find "$CRAFT_PART_INSTALL"/ -type d -empty -delete
      mkdir -p "$CRAFT_PART_INSTALL"/build-tools
      cp build-tools/* "$CRAFT_PART_INSTALL"/build-tools
    prime:
    - usr/share/doc/network-manager/copyright
    - usr/share/doc/libnm0/copyright
    - usr/share/doc/dnsmasq-base/copyright
    - usr/share/doc/network-manager/changelog.*
    - usr/share/doc/libnm0/changelog.*
    - usr/share/doc/dnsmasq-base/changelog.*
    stage: []
  dnsmasq:
    after:
    - stack-snaps-tools
    plugin: make
    source: https://git.launchpad.net/ubuntu/+source/dnsmasq
    source-type: git
    source-branch: applied/ubuntu/resolute-proposed
    build-packages:
    - build-essential
    make-parameters:
    - PREFIX=/
    override-build: |
      set -ex
      "/build/network-manager-snap-26/stage"/build-tools/check-versions dnsmasq-base no
      git apply "/build/network-manager-snap-26"/snap-patch/dnsmasq.patch
      craftctl default
      # Strip binaries
      find "$CRAFT_PART_INSTALL"/ -executable -type f | xargs file -Ni |
          grep 'application/x-.*executable\|application/x-.*sharedlib' | cut -d: -f1 | xargs strip
    prime:
    - sbin/dnsmasq
    stage-packages: []
    stage: []
  networkmanager:
    after:
    - stack-snaps-tools
    plugin: meson
    source: https://git.launchpad.net/ubuntu/+source/network-manager
    source-type: git
    source-branch: applied/ubuntu/resolute-proposed
    build-packages:
    - meson
    - gettext
    - libglib2.0-dev
    - ppp-dev
    - libselinux1-dev
    - libaudit-dev
    - libgnutls28-dev
    - uuid-dev
    - systemd-dev
    - libsystemd-dev
    - libudev-dev
    - libgirepository1.0-dev
    - gobject-introspection
    - python3-gi
    - libpsl-dev
    - libcurl4-gnutls-dev
    - gtk-doc-tools
    - libdbus-1-dev
    - libglib2.0-doc
    - libmm-glib-dev
    - libndp-dev
    - libreadline-dev
    - libnewt-dev
    - libteam-dev
    - libjansson-dev
    - libbluetooth-dev
    - valac
    - polkitd
    - libpolkit-gobject-1-dev
    - dbus
    - python3-dbus
    - python3-pexpect
    - iproute2
    - libyaml-dev
    - libnetplan-dev
    - netplan.io
    - intltool
    - libnss3-dev
    - libnvme-dev
    meson-parameters:
    - -Dprefix=/usr
    - -Dlibdir=lib
    - -Dsysconfdir=/etc
    - -Dlocalstatedir=/var
    - -Druntime_dir=/run
    - -Dqt=false
    - -Ddhcpcd=false
    - -Ddhclient=false
    - -Ddnsmasq=/snap/network-manager/current/sbin/dnsmasq
    - -Diptables=/sbin/iptables
    - -Dsystemd_journal=true
    - -Dlibexecdir=/snap/network-manager/current/usr/lib/NetworkManager
    - -Dpppd=/snap/network-manager/current/usr/sbin/pppd
    - -Dpppd_plugin_dir=/snap/network-manager/current/usr/lib/pppd/2.5.2/
    - -Dsystemdsystemunitdir=/usr/lib/systemd/system
    - -Dudev_dir=/usr/lib/udev
    - -Dcrypto=gnutls
    - -Dsession_tracking=no
    - -Dsuspend_resume=systemd
    - -Dmodem_manager=true
    - -Dnmtui=true
    - -Dnmcli=true
    - -Dselinux=false
    - -Dtests=yes
    - -Dlibaudit=no
    - -Dnetplan=true
    - -Dpolkit=false
    - -Dppp=true
    - -Difupdown=true
    - -Dintrospection=true
    - -Ddocs=false
    - -Dconcheck=true
    - -Dteamdctl=true
    - -Dwarning_level=1
    - -Dmodify_system=false
    - -Dovs=false
    - -Dnm_cloud_setup=false
    - -Dc_args=['-O2','-Wl,-z,relro,-z,now','-pie','-fpie']
    override-build: |
      set -ex

      # Download VPN packages here, we cannot just stage as they pull
      # the NM package which will conflict with our build.
      apt download network-manager-openvpn
      dpkg -x network-manager-openvpn_*.deb "$CRAFT_PART_INSTALL"/

      # Apply patches in SRC directory, as the meson plugin won't copy sources
      # in build dir after the pull step
      cd "$CRAFT_PART_SRC"
      "/build/network-manager-snap-26/stage"/build-tools/check-versions network-manager yes
      git config user.email "snapcraft@canonical.com"
      git config user.name "snapcraft"
      git am "/build/network-manager-snap-26"/snap-patch/networkmanager/*.patch
      cd "$CRAFT_PART_BUILD"

      # re-create configure
      craftctl default
      # Strip binaries
      find "$CRAFT_PART_INSTALL"/ -executable -type f | xargs file -Ni |
          grep 'application/x-.*executable\|application/x-.*sharedlib' | cut -d: -f1 | xargs strip

      # Run all tests NetworkManager ships by default
      # Hide the $SNAP env variable during testing, to prevent the netplan CLI
      # from using the snap fallback io.netplan.Netplan.Generate() DBus API as
      # that does not allow to pass a --root-dir argument, needed for testing
      _SNAP=$SNAP
      unset SNAP
      meson test -C "$CRAFT_PART_BUILD"
      SNAP=$_SNAP
      unset _SNAP
    stage-packages:
    - adduser=3.153ubuntu1
    - debconf=1.5.92
    - libcurl3t64-gnutls=8.18.0-1ubuntu2
    - libibverbs1=61.0-2ubuntu3
    - libjansson4=2.14-2build4
    - libldap2=2.6.10+dfsg-1ubuntu5
    - libmm-glib0=1.25.95-1ubuntu1
    - libndp0=1.9-1build1
    - libnewt0.52=0.52.25-1ubuntu3
    - libnghttp2-14=1.68.0-2
    - libpcap0.8t64=1.10.6-1ubuntu1
    - libpkcs11-helper1t64=1.31.0-1
    - libpsl5t64=0.21.2-1.1build2
    - librtmp1=2.4+20151223.gitfa8646d.1-3
    - libsasl2-2=2.1.28+dfsg1-9ubuntu3
    - libslang2=2.3.3-5build1
    - libssh2-1t64=1.11.1-1build2
    - libteamdctl0=1.31-1build4
    - mobile-broadband-provider-info=20251101-1build1
    - openvpn=2.7.0-1ubuntu1
    - ppp=2.5.2-1+1.2
    organize:
      snap/network-manager/current/usr/lib/pppd/2.5.2/nm-pppd-plugin.so: usr/lib/pppd/2.5.2/nm-pppd-plugin.so
      snap/network-manager/current/usr/lib/NetworkManager: usr/lib/NetworkManager
      usr/lib/x86_64-linux-gnu/NetworkManager: usr/lib/NetworkManager
    prime:
    - usr/bin/nmcli
    - usr/bin/nmtui
    - usr/bin/nmtui-connect
    - usr/bin/nmtui-edit
    - usr/bin/nmtui-hostname
    - usr/sbin/pppd
    - usr/lib/*/NetworkManager
    - usr/lib/pppd/2.5.2/nm-pppd-plugin.so
    - usr/lib/NetworkManager
    - usr/sbin/NetworkManager
    - usr/sbin/openvpn
    - etc/NetworkManager/*
    - usr/share/doc/libdbus-1-3/copyright
    - usr/share/doc/libcurl3t64-gnutls/copyright
    - usr/share/doc/libibverbs1/copyright
    - usr/share/doc/libjansson4/copyright
    - usr/share/doc/libldap2/copyright
    - usr/share/doc/libmm-glib0/copyright
    - usr/share/doc/libndp0/copyright
    - usr/share/doc/libnewt0.52/copyright
    - usr/share/doc/libnghttp2-14/copyright
    - usr/share/doc/libnm0/copyright
    - usr/share/doc/libpcap0.8t64/copyright
    - usr/share/doc/libpkcs11-helper1t64/copyright
    - usr/share/doc/libpsl5t64/copyright
    - usr/share/doc/librtmp1/copyright
    - usr/share/doc/libsasl2-2/copyright
    - usr/share/doc/libteamdctl0/copyright
    - usr/share/doc/libslang2/copyright
    - usr/share/doc/libssh2-1t64/copyright
    - usr/share/doc/mobile-broadband-provider-info/copyright
    - usr/share/doc/openvpn/copyright
    - usr/share/doc/ppp/copyright
    - usr/share/doc/network-manager-openvpn/copyright
    - usr/share/doc/libdbus-1-3/changelog.*
    - usr/share/doc/libcurl3t64-gnutls/changelog.*
    - usr/share/doc/libibverbs1/changelog.*
    - usr/share/doc/libjansson4/changelog.*
    - usr/share/doc/libldap2/changelog.*
    - usr/share/doc/libmm-glib0/changelog.*
    - usr/share/doc/libndp0/changelog.*
    - usr/share/doc/libnewt0.52/changelog.*
    - usr/share/doc/libnghttp2-14/changelog.*
    - usr/share/doc/libnm0/changelog.*
    - usr/share/doc/libpcap0.8t64/changelog.*
    - usr/share/doc/libpkcs11-helper1t64/changelog.*
    - usr/share/doc/libpsl5t64/changelog.*
    - usr/share/doc/librtmp1/changelog.*
    - usr/share/doc/libsasl2-2/changelog.*
    - usr/share/doc/libssh2-1t64/changelog.*
    - usr/share/doc/libteamdctl0/changelog.*
    - usr/share/doc/libslang2/changelog.*
    - usr/share/doc/mobile-broadband-provider-info/changelog.*
    - usr/share/doc/openvpn/changelog.*
    - usr/share/doc/ppp/changelog.*
    - usr/share/doc/network-manager-openvpn/changelog.*
    - usr/share/mobile-broadband-provider-info/*
    - usr/lib/*/libslang*
    - usr/lib/libnm*
    - usr/lib/*/libcurl-gnutls*
    - usr/lib/*/libdbus*
    - usr/lib/*/libssh2*
    - usr/lib/*/libjansson*
    - usr/lib/*/libpkcs11-helper*
    - usr/lib/*/liblber.so.2*
    - usr/lib/*/libldap.so.2*
    - usr/lib/*/libibverbs.so.1*
    - usr/lib/*/libmm-glib*
    - usr/lib/*/libnewt*
    - usr/lib/*/libndp*
    - usr/lib/*/libssh.so.4*
    - usr/lib/*/libnghttp2*
    - usr/lib/*/libpcap*
    - usr/lib/*/libpsl*
    - usr/lib/*/librtmp*
    - usr/lib/*/libsasl2*
    - usr/lib/*/libteamdctl*
    - usr/lib/openvpn/*
    - usr/lib/*/openvpn/plugins/*
    - usr/libexec/*openvpn*
    - -usr/lib/NetworkManager/nm-dhcp-helper
    - -usr/lib/NetworkManager/1.54.3/libnm-device-plugin-adsl.so
    - -usr/lib/NetworkManager/1.54.3/libnm-device-plugin-bluetooth.so
    - -usr/lib/NetworkManager/*/*.la
    - -usr/lib/libnm.la
    - -usr/lib/pkgconfig
    stage: []
architectures:
- amd64
image-info:
  build_url: https://launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+snap/network-manager-snap-26/+build/3134353
build-packages: []
build-snaps: []
primed-stage-packages:
- dnsmasq-base=2.92-1
- libcurl3t64-gnutls=8.18.0-1ubuntu2
- libdbus-1-3=1.16.2-2ubuntu4
- libibverbs1=61.0-2ubuntu3
- libjansson4=2.14-2build4
- libldap2=2.6.10+dfsg-1ubuntu5
- libmm-glib0=1.25.95-1ubuntu1
- libndp0=1.9-1build1
- libnewt0.52=0.52.25-1ubuntu3
- libnghttp2-14=1.68.0-2
- libnm0=1.54.3-2ubuntu3
- libpcap0.8t64=1.10.6-1ubuntu1
- libpkcs11-helper1t64=1.31.0-1
- libpsl5t64=0.21.2-1.1build2
- librtmp1=2.4+20151223.gitfa8646d.1-3
- libsasl2-2=2.1.28+dfsg1-9ubuntu3
- libslang2=2.3.3-5build1
- libssh2-1t64=1.11.1-1build2
- libteamdctl0=1.31-1build4
- mobile-broadband-provider-info=20251101-1build1
- network-manager=1.54.3-2ubuntu3
- openvpn=2.7.0-1ubuntu1
- ppp=2.5.2-1+1.2
