name: network-manager
version: 1.10.6-18-dev
summary: Network Manager
description: |
  NetworkManager is a system network service that manages your network
  devices and connections, attempting to keep active network connectivity
  when available. It manages ethernet, WiFi, mobile broadband (WWAN) and
  PPPoE devices, provides VPN integration with a variety of different
  VPN serivces.
  Please find the source code for this track at:
    https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/network-manager/+ref/snap-1.10
base: core18
confinement: strict
grade: stable

slots:
  service: network-manager

plugs:
  nmcli: network-manager
  wpa:
    interface: dbus
    bus: system
    name: fi.w1.wpa_supplicant1

layout:
  /sbin/resolvconf:
    symlink: $SNAP/sbin/resolvconf

hooks:
  configure:
    plugs:
      # network is needed to avoid some denials when using snapctl
      - network
      - network-setup-observe

apps:
  nmcli:
    command: usr/bin/nmcli
    plugs: [nmcli]
  nmtui:
    command: usr/bin/nmtui
    plugs: [nmcli]
  nmtui-connect:
    command: usr/bin/nmtui-connect
    plugs: [nmcli]
  nmtui-edit:
    command: usr/bin/nmtui-edit
    plugs: [nmcli]
  nmtui-hostname:
    command: usr/bin/nmtui-hostname
    plugs: [nmcli]
  networkmanager:
    command: bin/networkmanager
    daemon: simple
    slots: [service]
    plugs: [modem-manager, ppp, network-setup-observe, wpa, firewall-control,
            hardware-observe, network-setup-control, login-session-observe,
            network-observe]

parts:
  networkmanager-common:
    plugin: dump
    source: snap-common

  changelog:
    plugin: nil
    override-build: |
      cp "$SNAPCRAFT_PROJECT_DIR"/ChangeLog "$SNAPCRAFT_PART_INSTALL"/ChangeLog
    organize:
      ChangeLog: usr/share/doc/network-manager/ChangeLog

  dnsmasq:
    plugin: make
    source: https://git.launchpad.net/ubuntu/+source/dnsmasq
    source-type: git
    source-branch: applied/2.79-1ubuntu0.7
    build-packages:
      - build-essential
    make-parameters:
      - PREFIX=/
    override-build: |
      git apply "$SNAPCRAFT_PROJECT_DIR"/snap-patch/dnsmasq.patch
      snapcraftctl build
    filesets:
      binaries:
        - sbin/dnsmasq
    prime:
      - $binaries

  networkmanager:
    plugin: autotools
    source: https://git.launchpad.net/ubuntu/+source/network-manager
    source-type: git
    source-branch: applied/1.10.6-2ubuntu1.4
    build-packages:
      - intltool
      - libdbus-glib-1-dev
      - libdbus-1-dev
      - libglib2.0-dev
      - libiw-dev
      - libnl-3-dev
      - libnl-route-3-dev
      - libnl-genl-3-dev
      - ppp-dev
      - libgnutls28-dev
      - uuid-dev
      - systemd
      - libsystemd-dev
      - libudev-dev
      - libgirepository1.0-dev
      - gobject-introspection
      - python-gi
      - libpsl-dev
      - libcurl4-gnutls-dev
      - perl
      - libyaml-perl
      - libglib2.0-doc
      - libmm-glib-dev
      - libndp-dev
      - libreadline-dev
      - libnewt-dev
      - libteam-dev
      - libjansson-dev
      - dbus
      - python-dbus
      - quilt
      - xsltproc
      - iptables
      - gtk-doc-tools
    configflags:
      - --prefix=/usr
      - --libdir=/usr/lib
      - --disable-qt
      # dhcp handled by systemd client
      - --with-dhcpcd=no
      - --with-dhclient=no
      - --with-dnsmasq=/snap/$SNAPCRAFT_PROJECT_NAME/current/sbin/dnsmasq
      - --with-iptables=/sbin/iptables
      - --with-systemd-journal=yes
      - --libexecdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/NetworkManager
      - --with-pppd=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/sbin/pppd
      - --with-resolvconf=/snap/$SNAPCRAFT_PROJECT_NAME/current/sbin/resolvconf
      - --with-dnssec-trigger=/usr/lib/dnssec-trigger/dnssec-trigger-script
      - --with-systemdsystemunitdir=/lib/systemd/system
      - --with-udev-dir=/lib/udev
      - --with-crypto=gnutls
      # Explicitly disable session tracking, as it's not applicable on Ubuntu Core
      - --with-session-tracking=no
      - --with-suspend-resume=systemd
      - --with-modem-manager-1
      - --with-nmtui=yes
      - --with-nmcli=yes
      - --with-selinux=no
      - --with-tests
      - --with-libaudit=no
      - --without-dhcpcanon
      # Explicitly disable polkit, as it's not applicable on Ubuntu Core
      - --disable-polkit
      - --disable-polkit-agent
      - --enable-ppp
      - --enable-ifupdown
      - --disable-config-plugin-ibft
      - --enable-introspection
      - --disable-gtk-doc
      - --enable-concheck
      - --enable-teamdctl
      - --enable-json-validation
      - --disable-more-warnings
      - --disable-modify-system
      - --disable-ovs
      # Set explicitly CFLAGS until lp: #1791946 is solved
      - CFLAGS=-O2
    override-build: |
      git config user.email "snapcraft@canonical.com"
      git config user.name "snapcraft"
      git am "$SNAPCRAFT_PROJECT_DIR"/snap-patch/networkmanager/*.patch

      # remove configure to trigger autotools
      rm ./configure
      snapcraftctl build

      # Run all tests NetworkManager ships by default
      make check
    stage-packages:
      - iputils-arping
      - libasn1-8-heimdal
      - libdbus-glib-1-2
      - libcurl3-gnutls
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libjansson4
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libmm-glib0
      - libnewt0.52
      - libnghttp2-14
      - libroken18-heimdal
      - libndp0
      - libpsl5
      - librtmp1
      - libsasl2-2
      - libteamdctl0
      - libslang2
      - libwind0-heimdal
      - ppp
      - resolvconf

    override-stage: |
      snapcraftctl stage
      patch -p1 < "$SNAPCRAFT_PROJECT_DIR"/snap-patch/resolvconf.patch

    filesets:
      binaries:
        - sbin/resolvconf
        - usr/bin/arping
        - usr/bin/nmcli
        - usr/bin/nmtui
        - usr/bin/nmtui-connect
        - usr/bin/nmtui-edit
        - usr/bin/nmtui-hostname
        - usr/sbin/pppd
        - usr/lib/*/NetworkManager
        - usr/lib/pppd/2.4.5/nm-pppd-plugin.so
        - usr/lib/NetworkManager
        - usr/sbin/NetworkManager
      configs:
        - etc/NetworkManager/*
        - etc/resolvconf/update.d/libc
      docs:
        - usr/share/doc/dnsmasq/copyright
        - usr/share/doc/iputils-arping/copyright
        - usr/share/doc/libasn1-8-heimdal/copyright
        - usr/share/doc/libcurl3-gnutls/copyright
        - usr/share/doc/libdbus-glib-1-2/copyright
        - usr/share/doc/libgssapi3-heimdal/copyright
        - usr/share/doc/libhcrypto4-heimdal/copyright
        - usr/share/doc/libheimbase1-heimdal/copyright
        - usr/share/doc/libheimntlm0-heimdal/copyright
        - usr/share/doc/libhx509-5-heimdal/copyright
        - usr/share/doc/libjansson4/copyright
        - usr/share/doc/libkrb5-26-heimdal/copyright
        - usr/share/doc/libldap-2.4-2/copyright
        - usr/share/doc/libmm-glib0/copyright
        - usr/share/doc/libndp0/copyright
        - usr/share/doc/libnewt0.52/copyright
        - usr/share/doc/libnghttp2-14/copyright
        - usr/share/doc/libpcap0.8/copyright
        - usr/share/doc/libpsl5/copyright
        - usr/share/doc/libroken18-heimdal/copyright
        - usr/share/doc/librtmp1/copyright
        - usr/share/doc/libsasl2-2/copyright
        - usr/share/doc/libslang2/copyright
        - usr/share/doc/libteamdctl0/copyright
        - usr/share/doc/libwind0-heimdal/copyright
        - usr/share/doc/network-manager/copyright
        - usr/share/doc/ppp/copyright
        - usr/share/doc/resolvconf/copyright
      libs:
        - lib/resolvconf/list-records
        - lib/*/libnewt*
        - lib/*/libslang*
        - usr/lib/libnm*
        - usr/lib/*/libasn1*
        - usr/lib/*/libcurl-gnutls*
        - usr/lib/*/libdbus-glib*
        - usr/lib/*/libgssapi*
        - -usr/lib/*/libgssapi_krb5*
        - usr/lib/*/libhcrypto*
        - usr/lib/*/libheimbase*
        - usr/lib/*/libheimntlm*
        - usr/lib/*/libhx509*
        - usr/lib/*/libip4tc*
        - usr/lib/*/libip6tc*
        # required for teamdctl
        - usr/lib/*/libjansson*
        - usr/lib/*/libkrb5*26*
        - usr/lib/*/liblber-2.4*
        - usr/lib/*/libldap_r-2.4*
        - usr/lib/*/liblzma*
        - usr/lib/*/libmm-glib*
        - usr/lib/*/libndp*
        - usr/lib/*/libnghttp2*
        - usr/lib/*/libpcap*
        - usr/lib/*/libpsl*
        - usr/lib/*/libroken*
        - usr/lib/*/librtmp*
        - usr/lib/*/libsasl2*
        - usr/lib/*/libteamdctl*
        - usr/lib/*/libwind*
      unwanted:
        # We don't use dhclient so we don't need this helper
        - -usr/lib/NetworkManager/nm-dhcp-helper
        # Things we don't support yet and don't have to ship
        - -usr/lib/NetworkManager/libnm-device-plugin-adsl.so
        - -usr/lib/NetworkManager/libnm-device-plugin-bluetooth.so
        # Some additional build artifacts we do not need
        - -usr/lib/pkgconfig
    prime:
      - $binaries
      - $configs
      - $docs
      - $libs
      - $unwanted

  # This part is to make sure we get notifications from the review tools
  networkmanager-phony:
    after: [ networkmanager-common, changelog, dnsmasq, networkmanager ]
    plugin: nil
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/stack-snaps-tools
    source-type: git
    build-packages:
      - python3-minimal
      - python3-yaml
    stage-packages:
      - network-manager
      - dnsmasq-base
    # Check versions and make sure nothing from the staged packages is installed
    override-build: |
      ./build-tools/cmp-stage-build.py \
          networkmanager network-manager dnsmasq dnsmasq-base
      rm -rf ../install/*
    # Find out packages not primed in the end, for CI consumption
    override-prime: |
      mkdir -p snap
      "$SNAPCRAFT_PART_SRC"/build-tools/find-non-primed-pkgs.sh \
          "$SNAPCRAFT_PROJECT_DIR" snap/unstage.txt
