name: network-manager
version: 1.22.10-14-dev
summary: Network Manager
description: |
  NetworkManager is a system network service that manages your network
  devices and connections, attempting to keep active network connectivity
  when available. It manages ethernet, WiFi, mobile broadband (WWAN) and
  PPPoE devices, provides VPN integration with a variety of different
  VPN serivces.
  Please find the source code for this track at:
    https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/network-manager/+ref/snap-1.22
base: core20
confinement: strict
grade: stable

# Since the uc20 network-manager snap currently defaults to the native
# netplan config plugin, the default format of connection files has
# switched from keyfile to netplan, thus a fresh from earlier tracks
# of network-manager will not work w/out post-refresh hook support to
# handle conversion of system connection files. For this reason, this
# version of the network-manager snap declares the epoch 1. If/when
# support is added to convert from keyfile to netplan, then the epoch
# will be adjusted accordingly.
epoch: 1

slots:
  service: network-manager

plugs:
  nmcli: network-manager
  wpa:
    interface: dbus
    bus: system
    name: fi.w1.wpa_supplicant1

# As we need netplan Generate from the remove hook
assumes:
  - snapd2.54

hooks:
  configure:
    plugs:
      # network is needed to avoid some denials when using snapctl
      - network
      - network-setup-observe
  remove:
    plugs:
      - network-setup-control

layout:
  /usr/lib/NetworkManager:
    bind: $SNAP/usr/lib/NetworkManager
  /etc/NetworkManager:
    # Using 'conf' to keep compatibility with older NM snaps. Another option
    # would be to copy around the systems connections when refreshing.
    bind: $SNAP_DATA/conf
  /usr/var/lib/NetworkManager:
    bind: $SNAP_DATA/usr/var/lib/NetworkManager
  /var/lib/NetworkManager:
    bind: $SNAP_DATA/var/lib/NetworkManager

apps:
  nmcli:
    command: usr/bin/nmcli
    plugs: [nmcli]
  nmtui:
    command: usr/bin/nmtui
    plugs: [nmcli]
  nmtui-connect:
    command: usr/bin/nmtui-connect
    plugs: [nmcli]
  nmtui-edit:
    command: usr/bin/nmtui-edit
    plugs: [nmcli]
  nmtui-hostname:
    command: usr/bin/nmtui-hostname
    plugs: [nmcli]
  networkmanager:
    command: bin/networkmanager
    daemon: simple
    slots: [service]
    plugs: [modem-manager, ppp, network-setup-observe, wpa, firewall-control,
            hardware-observe, network-setup-control, login-session-observe,
            network-observe]

parts:
  networkmanager-common:
    plugin: dump
    source: snap-common

  changelog:
    plugin: nil
    override-build: |
      cp "$SNAPCRAFT_PROJECT_DIR"/ChangeLog "$SNAPCRAFT_PART_INSTALL"/ChangeLog
    organize:
      ChangeLog: snap/ChangeLog

  # Get aux scripts so they can be used in other parts. Also, stage
  # packages we rebuild later to get copyright and ensure they are in
  # the manifest.
  stack-snaps-tools:
    plugin: nil
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/stack-snaps-tools
    source-type: git
    build-packages:
      - dpkg-dev
      - git
    stage-packages:
      - dnsmasq-base
      - network-manager
    override-build: |
      set -ex
      find "$SNAPCRAFT_PART_INSTALL"/ -type f,l \
                -not -path "$SNAPCRAFT_PART_INSTALL"/'usr/share/doc/network-manager*' \
                -not -path "$SNAPCRAFT_PART_INSTALL"/'usr/share/doc/libnm0*' \
           -and -not -path "$SNAPCRAFT_PART_INSTALL"/'usr/share/doc/dnsmasq-base*' \
           -delete
      find "$SNAPCRAFT_PART_INSTALL"/ -type d -empty -delete
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/build-tools
      cp build-tools/* "$SNAPCRAFT_PART_INSTALL"/build-tools
    prime:
      - usr/share/doc/network-manager
      - usr/share/doc/libnm0
      - usr/share/doc/dnsmasq-base

  dnsmasq:
    after: [ stack-snaps-tools ]
    plugin: make
    source: https://git.launchpad.net/ubuntu/+source/dnsmasq
    source-type: git
    source-branch: applied/ubuntu/focal-updates
    build-packages:
      - build-essential
    make-parameters:
      - PREFIX=/
    override-build: |
      set -ex
      "$SNAPCRAFT_STAGE"/build-tools/check-versions dnsmasq-base no
      git apply "$SNAPCRAFT_PROJECT_DIR"/snap-patch/dnsmasq.patch
      snapcraftctl build
    filesets:
      binaries:
        - sbin/dnsmasq
    prime:
      - $binaries

  networkmanager:
    after: [ stack-snaps-tools ]
    plugin: autotools
    source: https://git.launchpad.net/ubuntu/+source/network-manager
    source-type: git
    source-branch: applied/ubuntu/focal-updates
    build-packages:
      - intltool
      - libdbus-glib-1-dev
      - libdbus-1-dev
      - libglib2.0-dev
      - libiw-dev
      - libnl-3-dev
      - libnl-route-3-dev
      - libnl-genl-3-dev
      - ppp-dev
      - libgnutls28-dev
      - uuid-dev
      - systemd
      - libsystemd-dev
      - libudev-dev
      - libgirepository1.0-dev
      - gobject-introspection
      - python-gi
      - libpsl-dev
      - libcurl4-gnutls-dev
      - perl
      - libyaml-perl
      - libglib2.0-doc
      - libmm-glib-dev
      - libndp-dev
      - libreadline-dev
      - libnewt-dev
      - libteam-dev
      - libjansson-dev
      - dbus
      - python-dbus
      - quilt
      - xsltproc
      - iptables
      - gtk-doc-tools
      - libnss3-dev
      - libnetplan-dev
      - netplan.io
      - libyaml-dev
    autotools-configure-parameters:
      - --prefix=/usr
      - --sysconfdir=/etc
      - --localstatedir=/var
      - --runstatedir=/run
      - --disable-qt
      # dhcp handled by systemd client
      - --with-dhcpcd=no
      - --with-dhclient=no
      - --with-dnsmasq=/snap/$SNAPCRAFT_PROJECT_NAME/current/sbin/dnsmasq
      - --with-iptables=/sbin/iptables
      - --with-systemd-journal=yes
      - --libexecdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/NetworkManager
      - --with-pppd=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/sbin/pppd
      - --with-pppd-plugin-dir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/pppd/2.4.5/
      - --with-resolvconf=/snap/$SNAPCRAFT_PROJECT_NAME/current/sbin/resolvconf
      - --with-dnssec-trigger=/usr/lib/dnssec-trigger/dnssec-trigger-script
      - --with-systemdsystemunitdir=/lib/systemd/system
      - --with-udev-dir=/lib/udev
      - --with-crypto=gnutls
      # Explicitly disable session tracking, as it's not applicable on Ubuntu Core
      - --with-session-tracking=no
      - --with-suspend-resume=systemd
      - --with-modem-manager-1
      - --with-nmtui=yes
      - --with-nmcli=yes
      - --with-selinux=no
      - --with-tests
      - --with-libaudit=no
      - --without-dhcpcanon
      # Explicitly disable polkit, as it's not applicable on Ubuntu Core
      - --disable-polkit
      - --disable-polkit-agent
      - --enable-ppp
      - --enable-ifupdown
      - --enable-introspection
      - --disable-gtk-doc
      - --enable-concheck
      - --enable-teamdctl
      - --enable-json-validation
      - --disable-more-warnings
      - --disable-modify-system
      - --disable-ovs
      - --without-nm-cloud-setup
      # Set explicitly CFLAGS until lp: #1791946 is solved
      - CFLAGS=-O2
    # Generated netplan patch from https://github.com/slyon/NetworkManager/tree/slyon/backend-1.22.10
    # git format-patch 1.22.10 --full-index --binary --stdout > ../0002-nm-netplan-keyfile.patch -- !(.gitignore)
    override-build: |
      set -ex
      "$SNAPCRAFT_STAGE"/build-tools/check-versions network-manager yes
      git config user.email "snapcraft@canonical.com"
      git config user.name "snapcraft"
      git am "$SNAPCRAFT_PROJECT_DIR"/snap-patch/networkmanager/*.patch

      # re-create configure
      ./autogen.sh
      snapcraftctl build

      # Run all tests NetworkManager ships by default
      # Hide the $SNAP env variable during testing, to prevent the netplan CLI
      # from using the snap fallback io.netplan.Netplan.Generate() DBus API as
      # that does not allow to pass a --root-dir argument, needed for testing
      _SNAP=$SNAP
      unset SNAP
      make check
      SNAP=$_SNAP
      unset _SNAP
    stage-packages:
      - iputils-arping
      - libasn1-8-heimdal
      - libbrotli1
      - libdbus-glib-1-2
      - libcurl3-gnutls
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libjansson4
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libmm-glib0
      - libnewt0.52
      - libnghttp2-14
      - libroken18-heimdal
      - libndp0
      - libpsl5
      - librtmp1
      - libsasl2-2
      - libteamdctl0
      - libslang2
      - libssh-4
      - libwind0-heimdal
      - ppp
      - resolvconf

    override-stage: |
      snapcraftctl stage
      patch -p1 < "$SNAPCRAFT_PROJECT_DIR"/snap-patch/resolvconf.patch

    organize:
      snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/pppd/2.4.5/nm-pppd-plugin.so: usr/lib/pppd/2.4.5/nm-pppd-plugin.so
      snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/NetworkManager: usr/lib/NetworkManager

    filesets:
      binaries:
        - sbin/resolvconf
        - usr/bin/arping
        - usr/bin/nmcli
        - usr/bin/nmtui
        - usr/bin/nmtui-connect
        - usr/bin/nmtui-edit
        - usr/bin/nmtui-hostname
        - usr/sbin/pppd
        - usr/lib/*/NetworkManager
        - usr/lib/pppd/2.4.5/nm-pppd-plugin.so
        - usr/lib/NetworkManager
        - usr/sbin/NetworkManager
      configs:
        - etc/NetworkManager/*
        - etc/resolvconf/update.d/libc
      docs:
        - usr/share/doc/iputils-arping/copyright
        - usr/share/doc/libasn1-8-heimdal/copyright
        - usr/share/doc/libbrotli1/copyright
        - usr/share/doc/libcurl3-gnutls/copyright
        - usr/share/doc/libdbus-glib-1-2/copyright
        - usr/share/doc/libgssapi3-heimdal/copyright
        - usr/share/doc/libhcrypto4-heimdal/copyright
        - usr/share/doc/libheimbase1-heimdal/copyright
        - usr/share/doc/libheimntlm0-heimdal/copyright
        - usr/share/doc/libhx509-5-heimdal/copyright
        - usr/share/doc/libjansson4/copyright
        - usr/share/doc/libkrb5-26-heimdal/copyright
        - usr/share/doc/libldap-2.4-2/copyright
        - usr/share/doc/libmm-glib0/copyright
        - usr/share/doc/libndp0/copyright
        - usr/share/doc/libnewt0.52/copyright
        - usr/share/doc/libnghttp2-14/copyright
        - usr/share/doc/libpcap0.8/copyright
        - usr/share/doc/libpsl5/copyright
        - usr/share/doc/libroken18-heimdal/copyright
        - usr/share/doc/librtmp1/copyright
        - usr/share/doc/libsasl2-2/copyright
        - usr/share/doc/libslang2/copyright
        - usr/share/doc/libssh-4/copyright
        - usr/share/doc/libteamdctl0/copyright
        - usr/share/doc/libwind0-heimdal/copyright
        - usr/share/doc/ppp/copyright
        - usr/share/doc/resolvconf/copyright
      libs:
        - lib/resolvconf/list-records
        - lib/*/libslang*
        - usr/lib/libnm*
        - usr/lib/*/libasn1*
        - usr/lib/*/libbrotli*
        - usr/lib/*/libcurl-gnutls*
        - usr/lib/*/libdbus-glib*
        - usr/lib/*/libgssapi*
        - -usr/lib/*/libgssapi_krb5*
        - usr/lib/*/libhcrypto*
        - usr/lib/*/libheimbase*
        - usr/lib/*/libheimntlm*
        - usr/lib/*/libhx509*
        - usr/lib/*/libip4tc*
        - usr/lib/*/libip6tc*
        # required for teamdctl
        - usr/lib/*/libjansson*
        - usr/lib/*/libkrb5*26*
        - usr/lib/*/liblber-2.4*
        - usr/lib/*/libldap_r-2.4*
        - usr/lib/*/liblzma*
        - usr/lib/*/libmm-glib*
        - usr/lib/*/libnewt*
        - usr/lib/*/libndp*
        - usr/lib/*/libnghttp2*
        - usr/lib/*/libpcap*
        - usr/lib/*/libpsl*
        - usr/lib/*/libroken*
        - usr/lib/*/librtmp*
        - usr/lib/*/libsasl2*
        - usr/lib/*/libssh*
        - usr/lib/*/libteamdctl*
        - usr/lib/*/libwind*
      unwanted:
        # We don't use dhclient so we don't need this helper
        - -usr/lib/NetworkManager/nm-dhcp-helper
        # Things we don't support yet and don't have to ship
        - -usr/lib/NetworkManager/1.22.10/libnm-device-plugin-adsl.so
        - -usr/lib/NetworkManager/1.22.10/libnm-device-plugin-bluetooth.so
        # Some additional build artifacts we do not need
        - -usr/lib/NetworkManager/*/*.la
        - -usr/lib/pkgconfig
    prime:
      - $binaries
      - $configs
      - $docs
      - $libs
      - $unwanted
