name: Publish to edge

on:
  push:
    branches:
      - snap-24

jobs:
  publish_to_edge:
    # self-hosted runner so we can access launchpad
    runs-on: self-hosted
    environment: beta
    steps:
      - name: Publish to edge
        env:
          LP_CREDENTIALS: ${{ secrets.LP_CREDENTIALS }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        uses: snapcore/system-snaps-cicd-tools/action-publish-edge@main
        with:
          # TODO: remove this filter when snapd 2.64 is released
          architectures: arm64,amd64,armhf
