#!/bin/sh -ex
# Copyright (C) 2021 Canonical Ltd
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Remove hook removes the netplan configuration that was written by the snap

netplan_cfg_p=/etc/netplan/00-default-nm-renderer.yaml

if [ -f "$netplan_cfg_p" ]; then
    rm -f "$netplan_cfg_p"
    # if we apply only, 00-default-nm-renderer.yaml is re-generated
    dbus-send --system --type=method_call --print-reply \
              --dest=io.netplan.Netplan /io/netplan/Netplan \
              io.netplan.Netplan.Generate
    dbus-send --system --type=method_call --print-reply \
              --dest=io.netplan.Netplan /io/netplan/Netplan \
              io.netplan.Netplan.Apply
fi
