#!/bin/sh -ex
# Copyright (C) 2021 Canonical Ltd
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Remove hook removes the netplan configuration that was written by the snap

rm -f /etc/netplan/00-default-nm-renderer.yaml /etc/netplan/90-NM-*.yaml

# If we apply only, 00-default-nm-renderer.yaml is re-generated, because
# NM is restarted by netplan. If we generate first, that is avoided.
# The reason is that on apply, netplan sees that the state in /run/
# involves NM, so it will try to notify it by restarting, even if it
# is not currently running. If we generate first, nothing in /run/ or
# in /etc/netplan/ will make netplan think that NM is being used.
dbus-send --system --type=method_call --print-reply \
          --dest=io.netplan.Netplan /io/netplan/Netplan \
          io.netplan.Netplan.Generate
# It looks like it might need a bit of time to create all files...
sleep 2
dbus-send --system --type=method_call --print-reply \
          --dest=io.netplan.Netplan /io/netplan/Netplan \
          io.netplan.Netplan.Apply
